# Simple test configuration to isolate PaperBee problems

GOOGLE_SPREADSHEET_ID: "dummy-spreadsheet-id"
GOOGLE_CREDENTIALS_JSON: "/Users/benjamin.weinert/git_repos/paperbee/dummy_creds.json" 
NCBI_API_KEY: "dummy-ncbi-key"
LOCAL_ROOT_DIR: "/Users/benjamin.weinert/git_repos/paperbee"

# Much simpler queries following original recommendations
query_biorxiv: "[single-cell] OR [scRNA-seq] OR [immunology]"
query_pubmed_arxiv: "[single-cell RNA sequencing] OR [scRNA-seq] OR [immunology]"

# Lower limits for testing
limit: 50
limit_per_database: 20

# Disable LLM filtering to test raw paper retrieval first
LLM_FILTERING: false

# All platforms disabled for testing
SLACK:
  is_posting_on: false
  bot_token: "dummy"
  channel_id: "dummy"
  app_token: "dummy"

TELEGRAM:
  is_posting_on: false
  bot_token: "dummy"
  channel_id: "dummy"

ZULIP:
  is_posting_on: false
  prc: "dummy"
  stream: "dummy"
  topic: "dummy"

MATTERMOST:
  is_posting_on: false
  url: "dummy"
  token: "dummy"
  team: "dummy"
  channel: "dummy"